### ISSUE TITLE
bug: Failed to initialized SDL: dsp: No such audio device with March 15th 2024 Raspberry Pi OS

### ISSUE THREAD

**Issue by AIWintermuteAI** [AIWintermuteAI/whispercpp#88]
### Describe the bug

Running on Raspberry Pi 4 with reSpeaker
```
whisper_init_state: kv cross size =    8.79 MB
ERROR: Failed to initialized SDL: dsp: No such audio device
Traceback (most recent call last):
  File "/home/pi/whispercpp/examples/stream/stream.py", line 30, in main
    transcription = self.transcriber.stream_transcribe(callback=self.store_transcript_handler, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venvs/whisper/lib/python3.11/site-packages/whispercpp/__init__.py", line 257, in stream_transcribe
    raise RuntimeError("Failed to initialize audio capture device.")
RuntimeError: Failed to initialize audio capture device.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/whispercpp/examples/stream/stream.py", line 100, in <module>
    transcriber.main(**vars(args))
  File "/home/pi/whispercpp/examples/stream/stream.py", line 32, in main
    assert transcription is not None, "Something went wrong!"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Something went wrong!
```

### Environment

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux

**Comment by AIWintermuteAI** [comment]
Possible workaround - use older Raspberry Pi OS image, 
https://downloads.raspberrypi.org/raspios_lite_arm64/images/
raspios_lite_arm64-2023-10-10
which was used originally.

I'm traveling in June, will be back to fixing it the beginning of July.

**Comment by MrDavid949** [comment]
Great video on YT :) I'm also seeing the same issue described above, kernel version 6.6.31+rpt-rpi-v8

**Comment by CameronMccutcheon02** [comment]
Having a similar issue with the _list_audio_devices_ argument. 

Not using a reSpeaker, instead using a USB webcam I had lying around which has an audio channel. Should return something on list_audio_devices but returns the same: ERROR: Failed to initialized SDL: dsp: No such audio device

Kernel Version: 6.6.20+rpt-rpi-v8
Python venv: Python 3.11.2

**Comment by AIWintermuteAI** [comment]
I've been fixing the CI issues and it's green again https://github.com/AIWintermuteAI/whispercpp/commit/cc9d09889dd1adf42e1008692b1106122c7d19b1
I'll work on SDK issue now

**Comment by lintweaker** [comment]
> I've been fixing the CI issues and it's green again [cc9d098](https://github.com/AIWintermuteAI/whispercpp/commit/cc9d09889dd1adf42e1008692b1106122c7d19b1) I'll work on SDK issue now

Nice! I just hit this bug yesterday, hopefully you'll manage to resolve the issue soon. Looking forward to trying the stream option

**Comment by AIWintermuteAI** [comment]
Okay, I got one step closer to solving it.
Looks like the issue with certain library not being installed during the wheel build (f#@#ing bazel with its f#@#ing "hermetic" builds, hermetic my a#@).

From the latest Raspberry Pi OS (`Linux raspberrypi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux`)
1) Clean the build cache
```
./tools/bazel clean --expunge
```
2) Install the libs
```
sudo apt-get install libsdl2-mixer-2.0-0
sudo apt-get install libudev-dev libasound2-dev libdbus-1-dev
```
3) Rebuild the whisper and reinstall it
```
./tools/bazel build //:whispercpp_wheel
pip install --force-reinstall $(./tools/bazel info bazel-bin)/*.whl
```
I'll do a clean build to see which one did the trick (likely libsdl2-mixer-2.0-0) and then update the README.

**Comment by AIWintermuteAI** [comment]
```
sudo apt-get install libasound2-dev
```
Only this command is necessary. You MUST rebuild and reinstall the bindings after.

**Comment by AIWintermuteAI** [comment]
Closed with https://github.com/AIWintermuteAI/whispercpp/commit/d549400b7480db936d669bb0039e188bad134cd9
